feat: Add comment box and mandatory functionality NUM-18
djaustin/question-master pull request #5
Opened 2021-09-27 14:34 UTC by tigs1995

2021-09-27 15:05 UTC, djaustin requested changes
This needs changes to the schema to make sure you can actually save this comment to the database

2021-09-27 15:05 UTC, djaustin commented on src/components/CommentComponent.tsx
> +    <Box as="label" p="8">
I don't think this needs to be its own component. Feels like a premature abstraction that doesn't provide us any benefit.

2021-09-27 15:05 UTC, djaustin commented on src/components/CommentComponent.tsx
> +        <Input onChange={onCommentChange} isInvalid/>
Register this input with react-hook-form let it manage this stuff for you

2021-09-27 15:05 UTC, djaustin commented on src/components/FeedbackButton.tsx
> +      <input {...getInputProps()} onChange={onFeedbackChange}/>
react-hook-form should handle all form state so we shouldn't have to add custom bits here to store the state of the score

2021-09-27 15:05 UTC, djaustin commented on src/pages/index.tsx
> +    if(feedbackValue == 1 && !comment){
the `handleSubmit` function on line 55 should be handling all our validation so we don't need to do it ourselves

2021-09-27 15:06 UTC, djaustin commented
Fix build issues form Vercel and code quality issues from codeclimate abov

2021-09-28 09:08 UTC, tigs1995 commented on src/components/CommentComponent.tsx
> +    <Box as="label" p="8">
I removed the component in the end

2021-09-28 09:11 UTC, djaustin approved these changes

2021-09-28 09:34 UTC, annabelkimber approved these changes

2021-09-28 09:37 UTC, merged